### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by rstropek** [blaumeise20/date-timeout-interval#1]
It would be good to add unit tests in order to verify the correctness of the code whenever changes will be made.

**Comment by blaumeise20** [comment]
Yeah, I merged your PR and all tests are passing. Maybe tests for interval would be possible.

**Comment by rstropek** [comment]
Yes, I think more tests for timeout and interval would be great. Additionally, I would consider creating a GitHub Action that verifies all tests whenever code is contributed to the *main* branch.

**Comment by blaumeise20** [comment]
I also thought about that.

**Comment by blaumeise20** [comment]
I‘m going to close this issue now, but I‘m still working on the tests.
