### ISSUE TITLE
`state` not set to 1 after starting timer

### ISSUE THREAD

**Issue by rstropek** [blaumeise20/date-timeout-interval#3]
If I understood the docs currently, `state` should be set to 1 after the timer has been started. This is currently not the case. Only `_state` is set. Is that intended? Pull request #2 contains a (currently skipped) test with which the potential bug can be reproduced.

**Comment by blaumeise20** [comment]
No, that's not intended. I fixed this here: https://github.com/blaumeise20/date-timeout-interval/commit/d9684f0b9006c114d780b96cf2393baada06a525
