### ISSUE TITLE
Constructor error when using with TypeScript

### ISSUE THREAD

**Issue by rstropek** [blaumeise20/date-timeout-interval#4]
Receiving syntax error when using `Timeout` constructor in TypeScript.

Reproduction:

```ts
import { Timeout } from 'date-timeout-interval';
const to = new Timeout(() => console.log('Done'), 1000, true);
```

Result: *error TS2554: Expected 0 arguments, but got 3.*

**Comment by blaumeise20** [comment]
Fixed with https://github.com/blaumeise20/date-timeout-interval/commit/eb5f42dafb918bc5b232824fb43ef5392434fc21
