### ISSUE TITLE
New Feature: Promisified version of `Timeout`

### ISSUE THREAD

**Issue by rstropek** [blaumeise20/date-timeout-interval#7]
The `Timeout` class currently works with a callback. I want to suggest a "promisified" version of it. Here is a sample of how the code could look like:

```js
(async () => {
  const to = new Timeout(1000); // Note that there is no callback in this method signature
  await to.toPromise();
  console.log('Done');
})();
```

The promise should be resolved if the timer completed. It should reject if the timer was stopped before completion.

What do you think about adding such a feature?

**Comment by blaumeise20** [comment]
That's definitely a good idea! But I would rather add a `.then` method, because you can directly await the timeout (correct my if I am wrong):
```ts
(async () => {
  const to = new Timeout(1000);
  await to;
  console.log('Done');
})();
```
Something like that.

**Comment by rstropek** [comment]
Looks nice, I am not sure if you could implement an API like that.

**Comment by blaumeise20** [comment]
I've implemented it. 1abae7a

**Comment by rstropek** [comment]
Love it! Thank you.
